name: CI Assemble and Publish

on:
  push:
#    tags:
#      - '^[0-9]+.*$'
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Spotless Check
        run: ./gradlew spotlessCheck --stacktrace

      - name: Lint
        run: ./gradlew lint --stacktrace

      - name: Upload Lint Report
        uses: actions/upload-artifact@v3
        with:
          name: kown-lint-report
          path: library/build/reports

      - name: Apply Signing
        if: ${{ github.event_name != 'pull_request' }}
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: ./.github/signing.sh

      - name: Assemble
        run: ./gradlew assemble --stacktrace

      - name: Publishing
        if: startsWith(github.ref, 'refs/tags/')
        run: ./gradlew publish